export const rankInfo = {
  MASTER: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/master.png',
  DIAMOND1: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/diamond1.png',
  DIAMOND2: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/diamond2.png',
  DIAMOND3: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/diamond3.png',
  DIAMOND4: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/diamond4.png',
  DIAMOND5: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/diamond5.png',
  PLATINUM1: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/platinum1.png',
  PLATINUM2: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/platinum2.png',
  PLATINUM3: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/platinum3.png',
  PLATINUM4: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/platinum4.png',
  PLATINUM5: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/platinum5.png',
  GOLD1: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/gold1.png',
  GOLD2: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/gold2.png',
  GOLD3: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/gold3.png',
  GOLD4: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/gold4.png',
  GOLD5: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/gold5.png',
  SILVER1: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/silver1.png',
  SILVER2: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/silver2.png',
  SILVER3: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/silver3.png',
  SILVER4: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/silver4.png',
  SILVER5: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/silver5.png',
  BRONZE1: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/bronze1.png',
  BRONZE2: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/bronze2.png',
  BRONZE3: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/bronze3.png',
  BRONZE4: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/bronze4.png',
  BRONZE5: 'https://d18ghgbbpc0qi2.cloudfront.net/pubg/rank_emblem/bronze5.png',
};